### ISSUE TITLE
W11 Rainmeter Mond not working in Powershell

### ISSUE THREAD

**Issue by RyzeNGrind** [meters-on-demand/cli#3]
```
mond --help
mond : The term 'mond' is not recognized as the name of a cmdlet, function, script file, or operable program. Check
the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ mond --help
+ ~~~~
    + CategoryInfo          : ObjectNotFound: (mond:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

 ryzengrind  mond
mond : The term 'mond' is not recognized as the name of a cmdlet, function, script file, or operable program. Check
the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ mond
+ ~~~~
    + CategoryInfo          : ObjectNotFound: (mond:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```
```
# Rainmeter Logs
System.Management.Automation.CmdletInvocationException: Cannot bind argument to parameter 'Path' because it is null. ---> System.Management.Automation.ParameterBindingValidationException: Cannot bind argument to parameter 'Path' because it is null.
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automati (Meters on Demand\Installer.ini - [PSRM])
```

**Comment by reisir** [comment]
Hi, I don't have W11 but I just released [v1.9.9](https://github.com/meters-on-demand/cli/releases/tag/v1.9.9), could you try installing that? It fixes a lot of things, including some install process issues, which this seems to be. It's missing some path, don't know which.

If v1.9.9 doesn't fix this, I'll take a better look at this issue.

**Comment by RyzeNGrind** [comment]
Thanks that seems to have fixed the issue!

**Comment by RyzeNGrind** [comment]
Sorry looks like the issue is still persisting after installer.ini says successfully installed.
```
mond version
mond : The term 'mond' is not recognized as the name of a cmdlet, function, script file, or operable
program. Check the spelling of the name, or if a path was included, verify that the path is correct
and try again.
At line:1 char:1
+ mond version
+ ~~~~
    + CategoryInfo          : ObjectNotFound: (mond:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

**Comment by reisir** [comment]
That error means PowerShell can't find mond. Did you restart PowerShell? It should find it in a new window. If it doesn't, run the Meters on Demand skin installer again and check the Rainmeter log for any errors. If there's no errors, I don't know what could cause this 🤔

**Comment by reisir** [comment]
I tested v1.9.9 on a fresh Windows 11 install, worked perfectly. Please report back if you have any issues. And remember you have to close and restart PowerShell after installation to make it load the updated environment PATH variable.

**Comment by RyzeNGrind** [comment]
Hey @reisir thanks for the detailed replies. I followed your instructions but was not able to get `mond` working yet. 



Tried to `Exit` and `Ctrl+R` > Run `powershell.exe` and tried typing `mond version` even after restart no difference. 
```
mond version
mond : The term 'mond' is not recognized as the name of a cmdlet, function, script file, or operable program. Check
the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ mond version
+ ~~~~
    + CategoryInfo          : ObjectNotFound: (mond:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

Am i supposed to load the installer.ini and save a layout so the loaded skin is always load on computer boot or reboot? I have already done this but it didn't make any difference for me.

**Comment by reisir** [comment]
You definitely do not need to run the installer multiple times...

At this point all we can do is tedious investigation and debugging. Check Skins\Meters on Demand\mond.log if there is one. Same for Skins\#Mond\mond.log

Also do this in PoweShell

```ps1
$env:path -split ";"
```

and see if the #Mond folder is in the list. If it's not, that would explain why it's not finding it.

Anyways I'm going to sleep, if these steps don't find anything I'm willing to do some live debugging with you tomorrow, just join the rainmeter discord server https://discord.gg/rainmeter

**Comment by RyzeNGrind** [comment]
```
C:\Users\REDACTED_USER\AppData\Local\oh-my-posh
C:\Program Files\ImageMagick-7.1.1-Q16-HDRI
c:\Users\REDACTED_USER\AppData\Local\Programs\cursor\resources\app\bin
C:\Windows\system32
C:\Windows
C:\Windows\System32\Wbem
C:\Windows\System32\WindowsPowerShell\v1.0\
C:\Windows\System32\OpenSSH\
C:\ProgramData\chocolatey\bin

C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR
C:\Program Files\dotnet\
C:\Program Files\Docker\Docker\resources\bin
C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common
C:\Program Files\PowerShell\7\
C:\Users\REDACTED_USER\AppData\Local\Microsoft\WindowsApps

C:\Users\REDACTED_USER\AppData\Local\spicetify
C:\Users\REDACTED_USER\AppData\Local\Programs\oh-my-posh\bin
c:\Users\REDACTED_USER\AppData\Local\Programs\cursor\resources\app\bin
C:\Users\REDACTED_USER\AppData\Local\Microsoft\WindowsApps

C:\Users\REDACTED_USER\AppData\Local\spicetify
C:\Users\REDACTED_USER\AppData\Local\Programs\oh-my-posh\bin
C:\Users\REDACTED_USER\AppData\Local\Microsoft\WinGet\Packages\Gyan.FFmpeg_Microsoft.Winget.Source_8wekyb3d8bbwe\ffmpeg-6.1.1-full_build\bin

C:\Users\REDACTED_USER\Documents\Rainmeter\Skins\#MondC:\Users\REDACTED_USER\.kube\
```

Seems like the last line seems off.

**Comment by reisir** [comment]
FYI: If you don't want your username to be public, you should also remove the screenshot of the Rainmeter log in your previous reply lol

And yeah that last line is the issue. It should be just #Mond and the .kube should be on the next line. Do you know what created the .kube folder? Or what program uses it? Because it's either that program messing up or the mond installation script and I'd like to be sure since mond hasn't messed up before.

I made the .kube folder manually, added it to PATH and ran mond install and it worked fine...

**Comment by RyzeNGrind** [comment]
I believe its vscode kubernetes extension i have that created .kube folder.

**Comment by reisir** [comment]
Well I don't know how this happened but you can fix it manually by editing your (user, not system) PATH variable. Windows has a nice GUI utility for this, you should be able to find it by searching "Environment variable" in start menu. 

Copy the current broken path somewhere, remove it and put the two separate paths in.
![image](https://github.com/meters-on-demand/cli/assets/93496808/4e495f61-a310-4ed4-bf6e-03edf186af4e)

**Comment by RyzeNGrind** [comment]
![image](https://github.com/meters-on-demand/cli/assets/14363544/b19a5bb7-929f-471d-98ea-6af51d82abc7)
Super confused why the env user variables is not showing the weird .kube line but the terminal does in powershell.
```
 REDACTED_USER  $env:path -split ";"
C:\Users\REDACTED_USER\AppData\Local\oh-my-posh
C:\Program Files\ImageMagick-7.1.1-Q16-HDRI
c:\Users\REDACTED_USER\AppData\Local\Programs\cursor\resources\app\bin
C:\Windows\system32
C:\Windows
C:\Windows\System32\Wbem
C:\Windows\System32\WindowsPowerShell\v1.0\
C:\Windows\System32\OpenSSH\
C:\ProgramData\chocolatey\bin

C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR
C:\Program Files\dotnet\
C:\Program Files\Docker\Docker\resources\bin
C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common
C:\Program Files\PowerShell\7\
C:\Users\REDACTED_USER\AppData\Local\Microsoft\WindowsApps

C:\Users\REDACTED_USER\AppData\Local\spicetify
C:\Users\REDACTED_USER\AppData\Local\Programs\oh-my-posh\bin
c:\Users\REDACTED_USER\AppData\Local\Programs\cursor\resources\app\bin
C:\Users\REDACTED_USER\AppData\Local\Microsoft\WindowsApps

C:\Users\REDACTED_USER\AppData\Local\spicetify
C:\Users\REDACTED_USER\AppData\Local\Programs\oh-my-posh\bin
C:\Users\REDACTED_USER\AppData\Local\Microsoft\WinGet\Packages\Gyan.FFmpeg_Microsoft.Winget.Source_8wekyb3d8bbwe\ffmpeg-6.1.1-full_build\bin

C:\Users\REDACTED_USER\Documents\Rainmeter\Skins\#MondC:\Users\REDACTED_USER\.kube\
```

**Comment by RyzeNGrind** [comment]
I don't know what happened (unrelated: I was removing and adding NixOS-WSL distros) and after several restarts it seems the path fixed itself somehow.

```
 Workspaces  $env:path -split ";"
C:\Users\REDACTED_USER\AppData\Local\oh-my-posh
C:\Program Files\ImageMagick-7.1.1-Q16-HDRI
c:\Users\REDACTED_USER\AppData\Local\Programs\cursor\resources\app\bin
C:\Windows\system32
C:\Windows
C:\Windows\System32\Wbem
C:\Windows\System32\WindowsPowerShell\v1.0\
C:\Windows\System32\OpenSSH\
C:\ProgramData\chocolatey\bin
C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR
C:\Program Files\dotnet\
C:\Program Files\Docker\Docker\resources\bin
C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common
C:\Program Files\PowerShell\7\
C:\Users\REDACTED_USER\AppData\Local\Microsoft\WindowsApps
C:\Users\REDACTED_USER\AppData\Local\spicetify
C:\Users\REDACTED_USER\AppData\Local\Programs\oh-my-posh\bin
C:\Users\REDACTED_USER\Documents\Rainmeter\Skins\#Mond
C:\Users\REDACTED_USER\AppData\Local\Microsoft\WindowsApps
C:\Users\REDACTED_USER\AppData\Local\spicetify
C:\Users\REDACTED_USER\AppData\Local\Programs\oh-my-posh\bin
C:\Users\REDACTED_USER\AppData\Local\Microsoft\WinGet\Packages\Gyan.FFmpeg_Microsoft.Winget.Source_8wekyb3d8bbwe\ffmpeg-6.1.1-full_build\bin
C:\Users\REDACTED_USER\.kube\
 Workspaces  mond
Use 'mond alias' to add aliases to your PowerShell profile
Use 'mond help alias' for more information
Use 'mond config AskAlias false' to suppress this message

update
 updates the skins list

install [-Skin] <fullName> [-Force]
 installs the specified skin

list [-Unmanaged]
 lists installed skins. use -Unmanaged to list manually installed skins

search [-Query] <keyword> [-Property <property>]
 searches the skin list

upgrade [-Skin] <fullName> [-Force]
 upgrades the specified skin

uninstall [-Skin] <fullName> [-Force]
 uninstalls the specified skin

restore [-Skin] <fullName> [-Force]
 restores an upgraded or uninstalled skin from @Backup

version
 prints the MonD version

alias
 adds Set-Alias calls to your PowerShell $PROFILE
 aliases speed up mond by skipping the cmd invocation
 if you use both PowerShell 5 and 7, you'll have to run 'mond alias' in both

help [-Command] [dev]
 show this help. use 'mond help dev' for a list of dev commands

Check out the Meters on Demand wiki! https://docs.rainmeter.skin
```
